services:
  shatalov-ly-netology-prometheus:
    image: prom/prometheus:latest
    container_name: shatalov-ly-netology-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - shatalov-ly-my-netology-hw
    restart: unless-stopped
    depends_on:
      - shatalov-ly-netology-pushgateway

  shatalov-ly-netology-pushgateway:
    image: prom/pushgateway:latest
    container_name: shatalov-ly-netology-pushgateway
    ports:
      - "9091:9091"
    networks:
      - shatalov-ly-my-netology-hw
    restart: unless-stopped

  shatalov-ly-netology-grafana:
    image: grafana/grafana:latest
    container_name: shatalov-ly-netology-grafana
    ports:
      - "80:3000"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    volumes:
      - ./grafana/custom.ini:/etc/grafana/custom.ini:ro
      - grafana_data:/var/lib/grafana
    networks:
      - shatalov-ly-my-netology-hw
    restart: unless-stopped
    depends_on:
      - shatalov-ly-netology-prometheus

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  shatalov-ly-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
